trigger:
  - main

pool:
  name: KuduWallet-pool   # your self-hosted Windows agent

stages:

# -------------------------
# BACKEND (.NET)
# -------------------------
- stage: Backend
  displayName: Build Backend
  jobs:
  - job: BackendJob
    displayName: Backend Job
    steps:

    - checkout: self

    - task: UseDotNet@2
      displayName: Setup .NET
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - script: dotnet restore
      displayName: Restore
      workingDirectory: KuduWallet.API

    - script: dotnet build --no-restore
      displayName: Build
      workingDirectory: KuduWallet.API

    - script: dotnet test --no-build
      displayName: Test
      workingDirectory: KuduWallet.API


# -------------------------
# FRONTEND (React)
# -------------------------
- stage: Frontend
  displayName: Build Frontend
  jobs:
  - job: FrontendJob
    displayName: Frontend Job
    steps:

    - checkout: self

    - task: NodeTool@0
      displayName: Setup Node
      inputs:
        versionSpec: '18.x'

    - script: npm install
      displayName: Install dependencies
      workingDirectory: KuduWalletClient

    - script: npm run build
      displayName: Build app
      workingDirectory: KuduWalletClient
