# render.yaml
services:
  - type: web
    name: kuduwallet-api
    runtime: docker
    region: frankfurt
    branch: main
    rootDir: KuduWallet.API
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Secret
        sync: false
      - key: Jwt__Issuer
        sync: false
      - key: Jwt__Audience
        sync: false
      - key: Google__ClientId
        sync: false
      - key: Google__ClientSecret
        sync: false
